<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.kodilla.exception.io.TestSuit" tests="2" skipped="0" failures="0" errors="0" timestamp="2021-05-19T13:12:57" hostname="DESKTOP-8LN2CGQ" time="0.002">
  <properties/>
  <testcase name="testWithAFoundException()" classname="com.kodilla.exception.io.TestSuit" time="0.001"/>
  <testcase name="testReadFile()" classname="com.kodilla.exception.io.TestSuit" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
